name: kalkulakos
description: Aplikasi KalkuKosan

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mysql1: ^0.20.0
  intl: ^0.19.0
  http: ^1.6.0
<<<<<<< HEAD
  
=======

>>>>>>> 96fe26ca4a33d28284d4a10260f1dc7590f1e306
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true